apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      web: conversao-temperatura
  template:
    metadata:
      labels:
        web: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: kubedevio/conversao-temperatura:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    web: conversao-temperatura
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
